### ISSUE TITLE
List all scripts from remote repositories

### ISSUE THREAD

**Issue by przemoc** [cfillion/reapack#12]
Being able to browse all scripts combined from all repositories (i.e. not only enabled) would be great.
It would require some new window like Packages tab from About repository window with obligatory filter (as I wrote in other issue).

It would greatly enhance discoverability factor, as you wouldn't need to go into all repositories About windows. At this moment you have to install all repositories to browse them conveniently (in Package Browser), which shouldn't be required.

**Comment by cfillion** [comment]
Disabling a repository is just a way to soft-uninstall it while still keeping it around for later. (And repositories do not need to be installed to be in the browser, only enabled)

I'm considering enabling all repositories by default to simplify the setup process, it seems like that would solve this as well.

**Comment by przemoc** [comment]
So what are the exact semantics of enabling repository? Its index XML simply becomes tracked by ReaPack?

If it's like that, then I think enabling all repositories by default makes really sense. I would even suggest replacing current Enabled column with column inserted as very first one with no label, where only tick mark (✓) could be put. By default all repositories would be enabled (ticked), but there is still a need to support disabling one by user (I think it should be available only from RBM/context menu, because it won't be commonly performed operation), like in case of removed repository, etc., to avoid getting errors.

---

To be honest I thought enabling repository installed it, but I guess the confusion may came from the fact that when managing repositories you can only enable them IIRC (no Windows w/ Reaper in sight atm, cannot recheck), but when you are in its about dialog you can only install it, so it's kind of incosistent in v1.0.

**Comment by cfillion** [comment]
"Synchronize packages" and the package browser use enabled repositories only. Disabling a repository is roughly the equivalent of commenting it in a text configuration file.

Checkboxes would be nice but they are harder to implement on OS X vs on Windows (SWELL doesn't have [LVS_EX_CHECKBOXES](https://msdn.microsoft.com/en-us/library/windows/desktop/bb774732(v=vs.85).aspx)). Maybe in the future.
