### ISSUE TITLE
Use sanitized script names

### ISSUE THREAD

**Issue by przemoc** [cfillion/reapack#14]
I think it would be really nice for ReaPack to use sanitized script names, i.e. without extension and author prefix. There is already a column for author and there could be additional column for extension.
(BTW the `author_` thing [use of underscore] is quite ugly, I'm not sure who came up with this style, but it's bad for a few reasons, aesthethical and technical, but I digress here).

Obviously within Reaper's Actions dialog there is no notion of additional info like author, so putting author name in filename (mostly for filtering purposes) is perfectly fine and I'm not criticizing such filenames at all.

Initially I thought that it can be achieved with `<reapack>`'s `desc` attribute, as it already has sanitized script names in [ReaTeam/ReaScripts](https://github.com/ReaTeam/ReaScripts)'s [index.xml](https://github.com/ReaTeam/ReaScripts/blob/master/index.xml) (so my [SiRPig](https://github.com/przemoc/REAPER-ReaScripts/blob/master/index.sh) also provides this attribute), but as far as I can tell it's not used in ReaPack at all.

(I'm using version available from the reapack.com, i.e. v1.0 built on Jun 10 2016 14:18:36.)

**Comment by cfillion** [comment]
The `desc` attribute is being added in ReaPack v1.1, currently in [beta](https://github.com/cfillion/reapack/releases):

![v1.1 browser](https://i.imgur.com/FFN32uG.gif)

**Comment by przemoc** [comment]
I had a hunch that it may be in the works. Great!
