### ISSUE TITLE
include themes?

### ISSUE THREAD

**Issue by jonbash** [cfillion/reapack#17]
I wonder if including themes might be a nice option? The repository system should keep it relatively clean. Thoughts?

**Comment by cfillion** [comment]
Yes! Support for themes is implemented in ReaPack v1.1 pre-releases. Thanks for reminding me of this. I've just created a new repository at this address: https://github.com/ReaTeam/Themes.

**Comment by cfillion** [comment]
v1.1rc3 released with the Themes repository added by default.
