### ISSUE TITLE
Feature :Filter by type

### ISSUE THREAD

**Issue by gaumondp** [cfillion/reapack#18]
Thanks for the great 1.1 version !

It would be handful to be able to filter by type. I'm often ending sorting by Type to get "effects only" so it's not that big a problem but with thousands of scripts it would be great nonetheless.

Merci !

**Comment by cfillion** [comment]
Click on the button with the package count to open the type filter menu: https://github.com/cfillion/reapack/wiki#filtering.

**Comment by gaumondp** [comment]
Thanks for giving me the instructions. 

May I suggest you add a triangle on the right of package count then, to indicate it's a menu. It would help others finding out by themselves.
