### ISSUE TITLE
'Install' flag does not work with multiple selections.

### ISSUE THREAD

**Issue by admiralbumblebee** [cfillion/reapack#20]
Select multiple packages in the browser, then select 'actions->install' (above versions) to flag them for installation.

Only the first item in the selection is flagged.

'Install/update selection' does work, however the menu labelling is confusing.

**Comment by cfillion** [comment]
This is the normal behavior. The difference between per-package and selection-wide actions is shown in the user guide: https://github.com/cfillion/reapack/wiki#actions.

Do you have an idea of a better labeling that would be less confusing?

**Comment by admiralbumblebee** [comment]
Is there any reason why there's a way to install 1 package when multiple are selected?

It seems to me that the menu-items should correlate to what is selected, single or multi-selection.

Am I perhaps missing some functionality here that would make that sub-optimal?

**Comment by cfillion** [comment]
It allows for more flexibility (especially when right-clicking). For example one can pick which version to install or open the documentation of one of the selected packages without having to discard his selection.

**Comment by admiralbumblebee** [comment]
The best suggestion I have is some better indication that then second 'install' menu option is for the item under the cursor. 

Perhaps something such as "Install _only_ v1.1" would better indicate that a single package is being acted upon.

**Comment by cfillion** [comment]
I could do it like this using a submenu:

![Idea 1](https://i.imgur.com/8YhgvkP.png)

**Comment by admiralbumblebee** [comment]
Excellent solution. Thank you.
