### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by Meta-Cortex** [cfillion/reapack#26]
**_Transaction report -> Errors tab_**

https://github.com/MichaelPilyavskiy/ReaScripts/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ���������� ��������� ������� ������, �.�. ������ ������ ������������ ���������� .

https://github.com/ReaTeam/JSFX/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ���������� ��������� ������� ������, �.�. ������ ������ ������������ ���������� .

https://reapack.com/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ���������� ��������� ������� ������, �.�. ������ ������ ������������ ���������� .

https://github.com/ReaTeam/LangPacks/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ���������� ��������� ������� ������, �.�. ������ ������ ������������ ���������� .

https://github.com/X-Raym/REAPER-ReaScripts/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ���������� ��������� ������� ������, �.�. ������ ������ ������������ ���������� .

https://github.com/ReaTeam/Extensions/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ���������� ��������� ������� ������, �.�. ������ ������ ������������ ���������� .

https://github.com/ReaTeam/Themes/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ���������� ��������� ������� ������, �.�. ������ ������ ������������ ���������� .

https://github.com/ReaTeam/ReaScripts/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ���������� ��������� ������� ������, �.�. ������ ������ ������������ ���������� .

**Comment by cfillion** [comment]
Which version of Windows is this? Also those � characters might be an encoding conversion bug. Which language is your version of Windows using?

Here are some thing you can try to troubleshoot this:

- If you use a firewall, make sure it allows full internet access to reaper.exe
- If you are in a network that requires traffic to go through a specific proxy server (eg. corporate environments), enter its address in Manage repositories > *Network settings*
- Try disabling *Verify the authenticity of SSL/TLS certificates (advanced)* in Manage repositories > *Network settings*

**Comment by Meta-Cortex** [comment]
Windows 7 service pack 1, russian language.

Thank you for reply I will try what you suggested.

**Comment by Meta-Cortex** [comment]
Last option fixed connection. 
I guess problem was old Windows that wasn't updated for a long time.

**Comment by cfillion** [comment]
Thanks for confirming! Fixing the error message character encoding bug in Russian Windows for the next version.
