### ISSUE TITLE
Unable to connect to reapack servers.

### ISSUE THREAD

**Issue by sonictim** [cfillion/reapack#27]
Hello,

I've been using reapack for awhile and it's great.  And then all of a sudden a few days ago, it simply stopped being able to connect to any of the servers and simply times out on me whenever I try to access them.  I can navigate to the githubs just fine in my web browser, so I don't think it's a problem with my internet being able to connect to the sites.  I think the problem stems from the fact I'm running macOS Catalina.  I can't be sure, but I think I stopped having the ability to connect after the most recent security update.  Perhaps it closed some kind of way the extension could communicate for security reasons?  I know I know.. Catalina is total fuckery, but I was forced into it when I upgraded my laptop.  Just thought I'd mention it to see if anyone else was having a similar problem.  Thank you!

**Comment by cfillion** [comment]
What are the exact error messages?

**Comment by sonictim** [comment]
Attached screenshot of error message.  
![Screen Shot 2020-06-11 at 9 11 07 PM](https://user-images.githubusercontent.com/63481516/84464038-484e9400-ac28-11ea-8e83-d5a9c7ec0350.png)

**Comment by cfillion** [comment]
Is the macOS firewall (or a third-party firewall) enabled?

**Comment by sonictim** [comment]
Yes.. I tried turning it off.. It didn't help.  I've made some progress
though.  I backed up all my preferences, wiped my Reaper Settings folder
and then did a clean install of reaper.  When I do that, and then installed
reapack, it worked fine.  But when I restored my preferences, it stopped
working.  I tried just removing the reapack.ini and reapack folder so
reapack would be a fresh start on reapack but with my current preferences.
That "freshly installed" reapack would timeout.  SO I must have a
preference set somewhere that's conflicting with reapack somehow.  Any
suggestions on where to look?

~Tim

**Comment by sonictim** [comment]
Okay, so it's something in my reaper.ini that's blocking reapack somehow.
I started with a fresh install and if I restore everything but my old
reaper.ini, reapack works great.  SO, i'm just going to abandon my old one
and start fresh again.. Attached is my faulty reaper.ini if you are
interested.

Cheers!

~Tim

**Comment by cfillion** [comment]
Interesting, thanks for investigating! GitHub didn't save the email attachment. Can you upload the problematic reaper.ini somewhere (eg. https://stash.reaper.fm)? I'll try to reproduce the issue in a Catalina virtual machine.

**Comment by sonictim** [comment]
stuck it on my google drive... Here's a link to download.  Hope this
helps.  For all i know, it may break non catalina installs, but i don't
really have a way to test.

https://drive.google.com/file/d/1ii1Dn6CKrzOqnEeYrMBAjUWj_UT5aPxw/view?usp=sharing

Thanks for getting back to me about this! I really appreciate it.

~T



 PROBLEMATIC (breaks reapack) reaper.ini
<https://drive.google.com/file/d/1ii1Dn6CKrzOqnEeYrMBAjUWj_UT5aPxw/view?usp=drive_web>

**Comment by sonictim** [comment]
Weird, it just happened again.  Today, Reapack just stopped wanting to communicate with the servers.  It would simply time out.  I then moved my reapack.ini elsewhere, started reaper and ran reapack, and it started working fine again.  I then took my old "bad" reapack.ini and moved it back deleting the freshly made one, and everything continued to work fine but with all my old settings!  Very strange indeed.

**Comment by cfillion** [comment]
It was reaper.ini before and now it's reapack.ini? Just restarting REAPER without touching the .ini doesn't work either? Very weird...

**Comment by sonictim** [comment]
OH hey!  yes..... I didn't realize the faulty ini had switched....  That is
super weird...

I'm running Catalina, so I'm just going to blame it on that... That's
actually probably Catalina's best feature.... knowing where to place the
blame!

Best,

~Tim
