### ISSUE TITLE
Support for REAPER VST plug-ins

### ISSUE THREAD

**Issue by helgoboss** [cfillion/reapack#28]
Hi! Is there a chance to add support for REAPER plug-ins that are not extensions but VST plug-ins? Or is it even already possible and I didn't find it in the docs? Thanks!

**Comment by cfillion** [comment]
ReaPack may only install files inside of the current REAPER install's resource folder. Installing VSTs is possible (and an Audio Plugin package type could be added), but users would need to add a folder to their VST search path.

**Comment by helgoboss** [comment]
There might be a way to do this without user action. It's possible to put VST plug-ins into `$RESOURCE_DIR/UserPlugins/FX` and REAPER will recognize them. I just asked Justin and he confirmed it. He mentioned that there might be some oddities when browsing such plug-ins via the "VST folders" method, but otherwise it should be okay.

**Comment by cfillion** [comment]
> It's possible to put VST plug-ins into $RESOURCE_DIR/UserPlugins/FX and REAPER will recognize them.

Ah! I didn't know about that folder. In this case, the Extensions package type (which writes in UserPlugins) should already be usable for installing VST plugins.

**Comment by helgoboss** [comment]
Great, happy to hear that! Then I will give it a try soon and close this ticket if it works.

**Comment by helgoboss** [comment]
@cfillion So I tried it and in general it works. There's one problem: If someone uses both REAPER 32-bit and 64-bit on Windows, REAPER so far just seems to load whatever DLL it finds first. If the architectures don't match, it's loaded in bridged mode, which of course doesn't work with REAPER extensions. A file name suffix doesn't help (e.g. `-x64`). This is not related to ReaPack, so I've asked Justin about it and he gives it a thought.

However, one thing about ReaPack's behavior caught my attention. I added the following two lines:

```xml
<source platform="win64" file="FX/ReaLearn-x64.dll">https://github.com/helgoboss/realearn/releases/download/v1.10.0-pre2/realearn-windows-x86_64.dll</source>
<source platform="win32" file="FX/ReaLearn-x86.dll">https://github.com/helgoboss/realearn/releases/download/v1.10.0-pre2/realearn-windows-i686.dll</source>
```
I successfully installed this via ReaPack in REAPER 64-bit (`FX/ReaLearn-x64.dll`). Afterwards I started REAPER 32-bit and ReaPack told me that ReaLearn would already be installed (with the option to reinstall) - although I never installed it in REAPER 32-bit. I tried it in the opposite direction with the same effect. Is it supposed to work like this?

**Comment by cfillion** [comment]
> Is it supposed to work like this?

When both a 32-bit and 64-bit install share the same resource folder, yes. Reinstalling the package on REAPER 32-bit removes the 64-bit-only files. Synchronizing detects missing files and would trigger a reinstall automatically.

To have both architectures installed at the same time, either the platform of both files could be set to "windows", or there could be two ReaLearn packages (so that both architectures are installable separately). (Packages which don't contain files for the current architecture are hidden.)

**Comment by helgoboss** [comment]
Understood. Thank you! Then I'll close this.
