### ISSUE TITLE
Can't get it to run!

### ISSUE THREAD

**Issue by cowboy** [cfillion/reapack#3]
I'm not sure what I'm doing wrong, but I've got Reaper v5.201/i386 installed on a Macbook Air running 10.7.5.

After downloading `reaper_reapack32.dylib`, I moved it into `~/Library/Application Support/REAPER/UserPlugins` and restarted Reaper, but didn't see the Extensions menu. (I've tried with both the 32- and 64-bit versions, just in case, but neither work.

Since then, I have downloaded the latest SWS Extensions, put it in that folder, restarted Reaper, and while I now see the Extensions menu (full of SWS stuff, yay!), I don't see ReaPack anywhere.

Help?

**Comment by cfillion** [comment]
Try this build: http://files.cfillion.tk/reapack/v1.0-ancient-osx/.

**Comment by cowboy** [comment]
That worked perfectly. It might be nice for ReaPack to officially support all the versions of OS X that Reaper, itself, does. Either way, thanks for all your hard work!

**Comment by cfillion** [comment]
This will be included in the next update. OS X 10.5 and 10.6 however do not ship libc++ for C++11 features so I don't know if ReaPack will be able to support those.

**Comment by cowboy** [comment]
Great!
