### ISSUE TITLE
Could not resolve host: raw.githubusercontent.com

### ISSUE THREAD

**Issue by kaureteny** [cfillion/reapack#30]
Hello
Thanks for helping! I'm using win10 64bit. All the software is 64bit version. I can lanch github by chrome. I follow the steps in User Guide, but error occurs. I don't know how to fix it, please help!
![99c9ec3ed61dbffaa32ec3fa28cee4a](https://user-images.githubusercontent.com/60374173/94328579-4b5a6e00-ffe6-11ea-8f80-bd57f2344dde.png)

**Comment by ducdemarch** [comment]
excuse me , but how was this problem fixed?
I am a reaper user facing the same problem with reapack.

**Comment by cfillion** [comment]
Internet connection or configuration issues are not a problem in ReaPack itself.

**Comment by ducdemarch** [comment]
> Internet connection or configuration issues on the user's side are not a problem in ReaPack itself.

Thank you,yes it's not the ReaPack. My description above seems not accurate. I will check the problem on my computer.But could you give me some tips, I have no idea where to start to fix my internet configuration. 
PS: I have the exactly same pop up window as above.

**Comment by cfillion** [comment]
Here's a few ideas to start with:

- A firewall might be blocking REAPER's executable from accessing the internet
- A VPN software might be active and interfering
- The network or computer might have misconfigured DNS servers
- The network might require all connections to go through a proxy server (to add one: ReaPack > Manage repositories > Options > Network settings)
- Trying on a different network and/or computer might help figure the cause

**Comment by ducdemarch** [comment]
> Here's a few ideas to start with:
> 
> * A firewall might be blocking REAPER's executable from accessing the internet
> * A VPN software might be active and interfering
> * The network or computer might have misconfigured DNS servers
> * The network might require all connections to go through a proxy server (to configure that: ReaPack > Manage repositories > Options > Network settings)
> * Trying on a different network and/or computer might help narrow down the cause
> 
> "Could not resolve host" means a DNS resolution issue. If none of the above apply, try googling that for further insight.

Thank you.
