### ISSUE TITLE
Make reapack installable globally

### ISSUE THREAD

**Issue by madskjeldgaard** [cfillion/reapack#31]
Hi! I've run into a very niche problem:
reapack is not installable systemwide on Linux.

SWS extensions for example may be installed in /opt/REAPER/Plugins but reapack can't which results in the following: 

![2020-09-26-114850_1920x1080_scrot](https://user-images.githubusercontent.com/22474608/94337915-5fa26900-ffee-11ea-9412-93e0dffa413e.png)

The reason for this request is to make it possible to package reapack for linux distros (which dont allow installations in users home folders)

**Comment by cfillion** [comment]
/opt/REAPER/Plugins is part of REAPER's install and should not be used for custom plugins. Next version (v1.2.4rc1) allows ReaPack to be installed as a symbolic link in UserPlugins.
