### ISSUE TITLE
ReaPack not usable on REAPER with dropbox settings sharing

### ISSUE THREAD

**Issue by dhilowitz** [cfillion/reapack#34]
I have a super niche problem. I use REAPER on two computer. I use Dropbox to share my REAPER settings directory between the two machines so that I can keep my settings in sync. The way that one does this on Mac is by symlinking the directory as follows
```
ln -s ~/Dropbox/Apps/REAPER "~/Application Support/REAPER"
```
For years, this was working well for me, but sometime last year a message start popping up:

```
ReaPack was not loaded from the standard extension path or its filename was altered.
Move or rename it to the expected location and retry.

Current: /Users/dhilowitz/Dropbox (Personal)/Apps/REAPER/UserPlugins/reaper_reapack-x86_64.dylib

Expected: /Users/dhilowitz/Library/Application Support/REAPER/UserPlugins/reaper_reapack-x86_64.dylib
```
Is there any way that I can continue to use ReaPack with my special configuration?

**Comment by cfillion** [comment]
Thanks for reporting this! It was due to a change in macOS Catalina. The next release of ReaPack will be adjusted for this. In the meantime, here's a fixed build: https://ci.appveyor.com/api/buildjobs/cbjg3o4bvvjp8w4o/artifacts/build%2Freaper_reapack-x86_64.dylib.

**Comment by dhilowitz** [comment]
Thanks so much for this!
