### ISSUE TITLE
Reapack.so file will not allow Reaper to be opened

### ISSUE THREAD

**Issue by sam-walsh4** [cfillion/reapack#35]
I have a Linux x86_64 version of Reaper, and I just attempted to download the corresponding Reapack file. Once I tried to reopen Reaper after placing the file in the plugins folder, Reaper would not open whatsoever. I followed the exact instructions in the Reapack user guide, and it won't work. I have also tried many ways of resolving the issue and (so far) nothing. Does anybody know what may be going on? I was hoping to get Reapack in my Reaper because there are some FX I need that the stock Reaper software doesn't have.

**Comment by cfillion** [comment]
Try running REAPER from the command line. This will show any errors that may be occurring when REAPER attempts to load ReaPack. (Such problems are often due to a dependent library (such as libcurl) not being installed on the system.)
