### ISSUE TITLE
Add macOS ARM as a platform

### ISSUE THREAD

**Issue by leafac** [cfillion/reapack#36]
Currently [the documentation](https://github.com/cfillion/reapack/wiki/Index-Format#source-element) only lists `darwin`, `darwin32`, and `darwin64` as platforms. It’d be nice if we could target the M1 Macs with something like `darwin-arm`.

**Comment by cfillion** [comment]
Thanks! I've updated the index format documentation. ReaPack v1.2.3.1 uses the `darwin-arm64` value. (It was documented on the [reapack-index wiki](https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation#provides).)

**Comment by leafac** [comment]
Oh, that’s awesome. Thank you!
