### ISSUE TITLE
macOS - Codesign or suggest how to avoid being block by macOS aggressive security

### ISSUE THREAD

**Issue by talaviram** [cfillion/reapack#41]
Downloaded reapack on an Intel machine with Big Sur.
Upon loading it will warn about the unverified dylib.

One option is the codesign but this requires and active Apple membership.

The open-source / quick option would be to add to the manual suggestion to remove the offending attribute.
`xattr -r -d com.apple.quarantine <reapack dylib location>`

**Comment by cfillion** [comment]
> The open-source / quick option would be to add to the manual suggestion to remove the offending attribute.

This can be done outside of the terminal via System Preferences > Security & Privacy > Allow Anyway. https://youtu.be/-ymOax9qFQY?t=187

I've added a note in the user guide.
