### ISSUE TITLE
Problem with creating new custom actions after reapack install

### ISSUE THREAD

**Issue by hassee85** [cfillion/reapack#42]
For some reason, I can't create custom actions in Reaper anymore. The command ID stays on zero (0).
 
I uninstalled everything and reinstalled Reaper, loaded my old config and reinstalled SWS.
At this stage, newly created custom actions generates a command ID.

The problem appears when i install Reapack, and synchronize and download all of repositories from Reapack.

After this, creating new Custom actions wont work. Command ID of the new script in the action window dispplays 0, and can't delete or edit the custom action.

Any ideas what I can be?

Not sure what this problem is caused by, but i felt i had no other choice than reporting it!

**Comment by cfillion** [comment]
REAPER's action list can only contain a limited amount of actions. Only install scripts and repositories that you actually need from ReaPack.

https://forum.cockos.com/showthread.php?t=243459
