### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by riotrah** [cfillion/reapack#43]
Hi, I want to first express extreme gratitude for your ( presumably ) thankless work and contribution to the REAPER community and OSS.

Second, I simply wanted to know what your thoughts are on the changes you've committed to master since the last release Dec 2020, and whether you believe they're worth the effort for you to release as a version, or if they warrant building from source.

I do not intend for this to come across as a beg for a release or a gesture of impatience or something - I just wanted to get your position on the last year of improvements.

Thanks again so much.

**Comment by cfillion** [comment]
> whether you believe they're worth the effort for you to release as a version

Yes, working on it.
