### ISSUE TITLE
Compatibility issue with Ubuntu 22.04

### ISSUE THREAD

**Issue by jahudka** [cfillion/reapack#47]
Hi, ReaPack depends on `libcrypto.so.1.1`, which doesn't seem to exist on Ubuntu 22.04, because the distribution upgraded to `libcrypto.so.3` (as part of an upgrade to `libssl3`).

A working temporary solution is to add the Impish security repository and install `libssl1.1` from there; e.g.:

```shell
# this URL works on the Raspberry Pi flavour of Ubuntu:
echo 'deb http://ports.ubuntu.com/ubuntu-ports impish-security main' | sudo tee /etc/apt/sources.list.d/impish-security.list
sudo apt-get update
sudo apt-get install libssl1.1
```

I don't have any idea on the possible system-wide ramifications of doing this, but for now I know of no other way to get ReaPack working on Ubuntu 22.04. Is it at all possible to add support for OpenSSL 3 so that ReaPack can pick at runtime whichever OpenSSL version is available?

**Comment by cfillion** [comment]
Working on adding support for OpenSSL 3 without losing compatibility with systems still shipping OpenSSL 1.1. In the meantime, ReaPack can be built from source on Ubuntu 22.04 to be linked against libssl3:

```sh
sudo apt install build-essentials cmake git php-cli libboost-dev catch2 libcurl4-openssl-dev libxml2-dev libssl-dev libsqlite3-dev zlib1g-dev
git clone --recursive https://github.com/cfillion/reapack.git
cd reapack
CXXFLAGS=-Wno-deprecated-declarations cmake -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --target install
```
(The last line also installs the produced binary into ~/.config/REAPER/UserPlugins`)

**Comment by acebone** [comment]
you have a typo in your apt install line: It's not 'build-essentials' but 'build-essential' (without the trailing 's')

**Comment by tubegeek** [comment]
I can confirm that the installation method described works - minus one "s" as noted above. Also with a stock theme, the Extensions menu is indeed present.

Thanks again and again for the development work. Amazing resource.

Question: which of the tools I installed for compiling can I safely uninstall now? Half a gig of development software may be too much to tote around if I'm not going to use it for much else. Thank you.

**Comment by cfillion** [comment]
> Question: which of the tools I installed for compiling can I safely uninstall now? 

They can all be uninstalled once ReaPack is compiled.

(Fixed the typo in the `apt` line)

**Comment by cfillion** [comment]
Binaries compatible with both OpenSSL 1.1 and 3.0 here: [x86 64-bit](https://ci.appveyor.com/api/buildjobs/np42k5yjlfmcgfe7/artifacts/build%2Freaper_reapack-x86_64.so) & [others](https://ci.appveyor.com/project/cfillion/reapack/builds/43476895) ("Artifacts" tab). Will do a release in the coming days.
