### ISSUE TITLE
HELP ME, PROBLEM IN X-RAY

### ISSUE THREAD

**Issue by gabriellreiscantor** [cfillion/reapack#55]
Hello, I'm a singer here from Brazil, I use x-ray, reapack for a while. My other laptop broke and is in repair and I'm using my sister's.

I took the reaper project from the hd of the other notebook, put everything right in it, downloaded the reaper and reappack, installed the x-ray... ok

My project already has the items, the letters, but when I activate the x-ray this message appears.

...rack items notes for dedicated web browser interface.lua:115: attempt to call a nil value (field 'ULT_GetMediaItemNote')

HELP ME....

![image](https://user-images.githubusercontent.com/68348511/180592599-65d33545-f850-4e78-b56b-a45a51dbe151.png)

**Comment by cfillion** [comment]
You're missing SWS (https://sws-extension.org/).
