### ISSUE TITLE
reapack crash on exit in REAPER 6.66 and earlier

### ISSUE THREAD

**Issue by schwaaa** [cfillion/reapack#56]
REAPER 6.66 and earlier expects the string passed in via Register("API_xxx", &regstruct) to persist as long as the function pointer is valid.  This causes a potential crash on exit because reapack's ~APIReg alters the string in-place before calling Register("-API_xxx").

This will be fixed in REAPER 6.67 and later, but you may want to handle the <= 6.66 case on your side by ensuring the string persists, either by passing in a persistent copy of m_help when registering, or leaving m_help untouched and passing in a local string when unregistering, or any other way.

**Comment by cfillion** [comment]
Fixing in both ReaPack and ReaImGui. Thank you!
