### ISSUE TITLE
Reapack doesn't support Reaper import/export funcitonality

### ISSUE THREAD

**Issue by daeavelwyn** [cfillion/reapack#61]
Hello,

I often need to export and import my Reaper settings so I masively use the option : 
-Preferences > General > Import configuration... (or Export configuration ...)

Actually, scripts are well exported and re-imported, but Reapack doesn't perform the kind of initial scan on my fresh imported Reaper version so I have to manually set those scripts into reapack (I use the action list that refers the scripts) and check them into the Reapack browser and finally install them whereas they are already present into the Reaper script folder.

To be more precise, let's take an example.
I have a 1st version of reaper we can call Reaper-portable1.
In this version I have SWS and Reapack installed and  several tweaks.
I install a new script with Reapack in the version, let's say Tukan's plugin for instance.

Now, I need to export this configuration in order to import it in another Reaper version we can call Reaper-localInstall
I can clearly see that scripts are exported as they should from Reaper-portable1 as it's easy to just check the exported archive.

In my Reaper-localInstall I'm now importing my configuration. ThisReaper- localInstall also have SWS and Reapack in the same version.
Reaper imports everything as it should, including the scripts. I know that because I can see them into the action list.
BUT if I open Reapack browser into this Reaper-localInstall version, those script aren't marked as installed and I need to install them once more to get everything to work.

So I'm not sure this is something Reapack is supposed to manage so may be I have to live with this behaviour regarding my specific use of this export/import functionality, in that case just let me know, otherwise, well, I guess it can be considered as an issue and that's why I'm wrinting those lines :)

BTW Reapack is an awesome tool, thanks a lot for all the hard work you put into it :)

**Comment by cfillion** [comment]
REAPER's import/export does not include everything and there is know way for extensions to add things to it.

Copying the entire resource folder is the only way to ensure all the missing data (not just ReaPack's) is transferred.

ReaPack has its own import/export feature: https://reapack.com/user-guide#offline-use.

**Comment by daeavelwyn** [comment]
Ok, thanks for pointing me the import/export directly inside ReaPack, it wil do the job :)
