### ISSUE TITLE
eror while syncing repos

### ISSUE THREAD

**Issue by finduuni** [cfillion/reapack#68]
I've checked for my firewall and network settings but error still appears. Tried to uninstall and install again repos - nothing works.
Its server problem

`https://github.com/ReaTeam/JSFX/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
`
`
https://github.com/MichaelPilyavskiy/ReaScripts/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
`
`
https://reapack.com/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
`
`
https://github.com/zaibuyidao/ReaScripts/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
`
`
https://github.com/ReaTeam/Extensions/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
`
`
https://github.com/X-Raym/REAPER-ReaScripts/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
`
`
https://github.com/ReaTeam/ReaScripts/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
`
`
https://github.com/ReaTeam/Themes/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
`
`
https://github.com/ReaTeam/LangPacks/raw/master/index.xml:
  SSL connect error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline. 
`

**Comment by cfillion** [comment]
This can be caused by many things in your network including VPN apps, proxy, corporate network limitations, firewall, etc...

Can't help narrow down the root cause on your end, however this can be bypassed by enabling "Verify the authenticity of SSL/TLS vertificates" in ReaPack > Manage repositories > Options > Network settings.

**Comment by finduuni** [comment]
Yea big thanks it worked!
