### ISSUE TITLE
Reapack refuses to read an index file created by reapack-index

### ISSUE THREAD

**Issue by myrrc** [cfillion/reapack#70]
Reapack-index version: 1.2.3
Reapack version: 1.2.4.3
Sample file produced: https://github.com/myrrc/reaper-keys/blob/128330f58eea559488a22a770917bb36365e3d63/index.xml
Reapack complains "Start tag expected, '<' not found"

**Comment by cfillion** [comment]
That's a link to GitHub's HTML web page. The link to the XML document is https://github.com/myrrc/reaper-keys/raw/128330f58eea559488a22a770917bb36365e3d63/index.xml (s/blob/raw/).
