### ISSUE TITLE
Reaper Crashes on Windows 11

### ISSUE THREAD

**Issue by manugentoo** [cfillion/reapack#76]
Hey bud! 

reporting this one

**Overview**
Reaper closes after opening, happens after installing reapack and reaper_kontrol.dll

**Environment**
Reaper Version: v7.09
OS: Windows 11 Pro Build 22631.3085

lemme know if you need the hardware specs

**Comment by cfillion** [comment]
Can you send the crash report from Windows Event Viewer?

**Comment by manugentoo** [comment]
Good to know this looks like its working now. Thanks bud!

> "May cause Reaper to crash on startup if another program has already claimed the keyboard MIDI device before Reaper starts. To avoid this start Reaper before e.g. running stand-alone Komplete Kontrol or stand alone Maschine Software simultaneously. Once Reaper is running any number of programs using the keyboard MIDI device can run simultaneously.
"
