### ISSUE TITLE
REAPER not detecting Reapack extension in MacOS Sonoma

### ISSUE THREAD

**Issue by EmNudge** [cfillion/reapack#78]
Running an M1 Max, mostly clean install of REAPER with SWS. 
Reaper does not seem to be picking up on the existence of the plugin in the UserPlugins folder. No opening dialog, no action available to add to the menu bar.

I did accidentally click on the dylib file at some point, which opened up the terminal. I'm wondering if this maybe triggered some file write somewhere, so it's been caching a bad value? Honestly unsure, just very confused.

**Comment by cfillion** [comment]
Make sure it's the correct architecture to match REAPER's (ARM64 if running natively on your M1, x86_64 if Rosetta is enabled). No harm installing both. I doubt opening it in the terminal would have done anything bad, but just it case you can try deleting & re-downloading it anyway.

Here's a video that covers installing ReaPack on macOS (most of the difficulty revolves around dealing with Apple's security theater...): https://youtu.be/Uu7AE98x-AM?t=149.

**Comment by EmNudge** [comment]
Yeah, I've tried redownloading a couple times and even adding both ARM and x86 files into the folder. Still absolutely nothing when I open REAPER. There doesn't seem to be an attempt to open the file by reaper, as I should get a security warning, which does happen when I try directly clicking the file.

**Comment by cfillion** [comment]
Is it in the correct REAPER install's UserPlugins folder? (Options > Show REAPER resource path in explorer/finder)

Assuming that it is, and under its original filename, it would be strange for it to not be picked up. There are no actions in the Action List with "ReaPack" at all, nor any reapack.ini created in the resource directory?

Could try starting REAPER from Terminal.app: it prints extension loading failures there.

```sh
/path/to/REAPER.app/Contents/MacOS/REAPER
```

For example:
![Screen Shot 2024-03-02 at 16 24 14](https://github.com/cfillion/reapack/assets/4297676/6d18c115-709e-40a8-8416-b2132496c222)

**Comment by EmNudge** [comment]
Yeah, I'm completely stumped. No errors.

I don't see any "reapack" properties in the reaper.ini file (but I do see SWS). There are no actions in the list with "reapack" in the name either. I ran `rg reapack .` in the Reaper directory and found no results (i.e. no text file contains reapack).

Is there any way to manually get Reaper to load the file instead of relying on it automatically picking it up from the folder?

**Comment by cfillion** [comment]
The last thing I can think of is trying to manually remove the quarantine attribute from the downloaded file:
```sh
xattr -d com.apple.quarantine ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack-*.dylib
```

**Comment by EmNudge** [comment]
That was it!

The file needed to be specifically named `reaper_reapack-*`. I didn't know this was a requirement. 
The file downloads directly as `ReaPack ARM64.dylib` and I didn't see instructions to rename it, just to drag it into the folder.

Thanks so much for helping debug this!
