### ISSUE TITLE
Contents missing when downloaded through ReaPack

### ISSUE THREAD

**Issue by tbdalgaard** [cfillion/reapack#83]
Hello.

I just noticed that some scripts are missing when downloaded through ReaPack. An example is the add chap prefix to project markers script created by acendan
You can see 
[This issue for more details](https://github.com/acendan/reascripts/issues/4" on his Github. But I don't know if it is an issue within ReaPack or something in the repo he has shared.

Hopefully we can sort this out. I really enjoy ReaPack and many of the scripts. :)

**Comment by cfillion** [comment]
Do you mean "acendan_Rename project markers with CHAP prefix for FLAC cues.lua"? It's listed in that repository's index.xml under "Rename Cue Markers". There's a few packages with that same name, which certainly doesn't look correct.

In any case, ReaPack only knows what a repositories tells it via index.xml, so anything missing or misnamed is up to the repository's maintainer to fix.
