### ISSUE TITLE
Problem with scrolling Lyrics (X-Ryam)

### ISSUE THREAD

**Issue by rennersf** [cfillion/reapack#87]
Dear, I'm using the X-Ryam Scripts with scrolling mode to see the lyrics on ipad screen. Everything is works almost well, but when arrives as from fourth lyrics verse, the next verse does not appear. In the other words, the verses scrolling stops. I need scroll manualy to center the lyrics on screen, else I can't see the next verse. What can I solve this inssue? PS: I alright have tested in other tablets and have updated the Reaper. It is same inssue.
![Captura de Tela 2024-10-04 às 20 50 59](https://github.com/user-attachments/assets/2b2fde39-aa6a-482a-a1b2-22d95e80e04f)

**Comment by X-Raym** [comment]
@rennersf Hi !

This is @cfillion reapack repository about reapack extension, it is not the place for discussing about my scripts.

Please contact me in PM: https://www.extremraym.com/en/contact/

For the contact message, put your reaper project .rpp file on a drive somewhere and paste the link in the email, and tell me the script you are using to push lyrics to the web interface.

See you there !

@cfillion ticket can be closed
