### ISSUE TITLE
Question: lua script that has to download  binaries, which syntaxis should be used?

### ISSUE THREAD

**Issue by tormyvancool** [cfillion/reapack#89]
For a ReaPack LUA Script  that needs to download binaries from a site, and put them into a specific subdir: which syntax should be used into the header?

I tried with

```
-- @provides
--   [data] thesubdir/binary.exe https://github.com/whatsoever/whatsoever/releases/latest/download/binary.exe
```

but it didn't do anything.

What's your hint please?

**Comment by cfillion** [comment]
The snippet above downloads from the specified URL and installs the file in Data/thesubdir as binary.exe.

I would recommend specifying a specific version when downloading resources instead of 'latest'.

**Comment by tormyvancool** [comment]
> The snippet above downloads from the specified URL and installs the file in Data/thesubdir as binary.exe.
> 
> I would recommend specifying a specific version when downloading resources instead of 'latest' and specifying the file is Windows-only + whether it's 32 or 64-bit so that it doesn't get installed on a platform where the user can't run it.

My point is that, by adopting the statement I wrote in LUA, not any binary is downloaded and not any "thesubdir" is created under "Data" when that LUA is installed. That's why I'm suspecting something is not correct on my statement.

**Comment by cfillion** [comment]
Are you referring to [this file](https://github.com/tormyvancool/TormyVanCool_ReaPack_Scripts/blob/b968039e4fceaa8121a8d8f5da12759b685ee255/TOST_MAIN.lua)? It's not in a subfolder (= category name) so reapack-index ignores it.

> NOTE: not sure it's possible to put a statement that identify each O.S. type.

See the documentation of reapack-index's provides tag:

https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation#provides
```
@provides
  [data win32] the_file_for_windows_x86_32bit.exe
  [data win64] the_file_for_windows_x86_64bit.exe
  [data linux-aarch64] the_file_for_linux_arm_64bit.exe
  etc
```

**Comment by tormyvancool** [comment]
> It's not in a subfolder (= category name) so reapack-index ignores it. If the .exe file is in your repository then you should not specify the download URL. Just the path.

So [various win64] subdir/binary.exe https.://blablabla ??

I'm rally getting crazy with. A simple thing that's requiring days :-/ Peharp the doc should be complete with more examples I think.

**Comment by cfillion** [comment]
With the package file in a category subfolder. And either no URL (if the .exe is in the repo) or a version-specific (or commit-specific) URL so that your users can correctly downgrade.

**Comment by tormyvancool** [comment]
> With the package file in a category subfolder. And either no URL (if the .exe is in the repo) or a version-specific (or commit-specific) URL to make your release immutable so that your users can correctly downgrade.

I tried also [various] but I want that binary inside a subfolder in various. I have not clue which syntaxis I have to use. Not a&ny idea. It's not reported into the doc I have seen. I'm thrown 2 days away for a line code simply because the syntaxis . Not clue what mit must be. 
Yes the URL must be there because it's not form my own repository. But it's the original one.

**Comment by cfillion** [comment]
>  I have not clue which syntaxis I have to use.

It's not an issue with your syntax, but rather the location of the file. reapack-index does not scan files that are at the root of the repository.

**Comment by tormyvancool** [comment]
> > I have not clue which syntaxis I have to use.
> 
> It's not an issue with your syntax, but rather the location of the file. reapack-index does not scan files that are at the root of the repository. So the whole TOST_MAIN.lua is just not read at all.

So what do you suggest? Because the idea is to download the binary from the URL into `Data/thesubdir`

```
-- @provides
--   [data windows] thesubdir/binary.exe https://github.com/whatsoever/whatsoever/releases/latest/download/binary.exe
```

Or also 
```
-- @provides
--   [various windows] thesubdir/binary.exe https://github.com/whatsoever/whatsoever/releases/latest/download/binary.exe
```

however nothing works

**Comment by cfillion** [comment]
You need to move TOST_MAIN.lua into a subdirectory.

**Comment by tormyvancool** [comment]
> You need to move TOST_MAIN.lua into a subdirectory. That subdirectory will be shown to the user as the package's category in ReaPack.

Tried right now. but not any binary is downloaded. At this point I give up.

**Comment by cfillion** [comment]
Are you using `reapack-index` to generate your index.xml?

**Comment by cfillion** [comment]
Works here (deleted the weird index.xml, then ran `reapack-index`):

![Screen Shot 2024-10-31 at 17 23 57](https://github.com/user-attachments/assets/5b7a776a-75ad-46f7-891a-faf2952ae57d)

**Comment by tormyvancool** [comment]
> Are you using `reapack-index` to generate your index.xml? Yours is strangely missing the `commit` attribute, and contains scripts at the root, which as mentioned above should not be indexed at all.

the XML you mean? I edit it manually each time. I also wrote it manually.

**Comment by cfillion** [comment]
Well that's the problem! ReaPack only reads index.xml. If you don't list those files in there, they won't get installed.

The metadata header, `@provides` etc, is only for `reapack-index` which uses it to generate the index.xml.

**Comment by tormyvancool** [comment]
> Well that's the problem! ReaPack only reads index.xml. If you don't list those files in there, they won't get installed.
> 
> The metadata header, `@provides` etc, is only for `reapack-index` which uses it to generate the index.xml.

So let me explain:

by using my index.xml library in ReaPack: it works perfectly.
But I wanted to test the script aside that index.xml to verify the .LUA itself could download the needed binaries.
In this way, I could merge teh .LUA I'm making (once finished) into the official ReaPack also by using the tool on your website, sure that it is working.

**Comment by cfillion** [comment]
> But I wanted to test the script aside that index.xml to verify the .LUA itself could download the needed binaries.

That's not a thing. The XML index is what tells ReaPack what to download and install. Nothing else.

The fancy metadata syntax at the top? That's just to make life easier for us humans. The `reapack-index` software is used to scan through time (the git history), read the packaging metadata, and automatically update the XML index.

**Comment by tormyvancool** [comment]
> > But I wanted to test the script aside that index.xml to verify the .LUA itself could download the needed binaries.
> 
> That's not a thing. The XML index is what tells ReaPack what to download and install. Nothing else.
> 
> The fancy metadata syntax at the top? That's just to make life easier for us humans. The `reapack-index` software is used to scan through time (the git history), read the packaging metadata, and automatically update the XML index.

Oh my gosh .. if you think I have made that `.xml` all manually ... and there was a software.  Years ago I watched a video of a knowledge guy: Leandro Facchinetti and he explained how to make it by hand and I'm doing it so ever since ... Ia tool like this is really welcome it wil make me safe

So if I have correctly understood: that tool `reapack-index` will scan the files, and by meeting the `@provides` will it generate the `<source>` tag into index.xml accordingly?

**Comment by cfillion** [comment]
> So if I have correctly understood: that tool reapack-index will scan the files, and by meeting the @provides will it generate the <source> tag into index.xml accordingly?

Exactly!

**Comment by cfillion** [comment]
Also check out this repository template: https://github.com/cfillion/reapack-repository-template.

It runs `reapack-index` automatically for you whenever a commit is pushed. So you don't even have to run `reapack-index` yourself.

**Comment by tormyvancool** [comment]
> > So if I have correctly understood: that tool reapack-index will scan the files, and by meeting the `@provides` will it generate the `<source>` tag into index.xml accordingly?
> 
> Exactly!

OMG that's explains why I was struggling ...

so, what I wanted , is:

- Once my script is released to you, it should be into the directory 
- `C:\Users\Tormy VanCool\AppData\Roaming\REAPER\Scripts\ReaTeam Scripts\Various`
- Inside that dir, wit will be created the `thesubdir` folder (it will be called `yt-dlp`  as you spotted already)
- Inside that folder will be downloaded the binary packages from the official GitHub repository.

So, is the @provides here below written correctly for such idea?

```
-- @provides
--   [various windows]  yt-dlp/yt-dlp.exe https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
```

will generate this tag? or should I modify the previous lien with a different syntax?
`<source file="yt-dlp/yt-dlp.exe">https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe</source>`

**Comment by tormyvancool** [comment]
YES got it

![image](https://github.com/user-attachments/assets/02f457ac-fa6d-490e-a1a9-e134fdbff5e6)
