### ISSUE TITLE
Trouble dling script index via proxy

### ISSUE THREAD

**Issue by stefankovatchev** [cfillion/reapack#9]
I'm trying to use reapack at work, and I was getting an SSL error. I asked around and got our proxy 
information but now I'm getting a download failed prompt [Error description: Couldn't connect to server].

I'm pretty sure I'm inputting the host:port correctly.

Is there any way to update a CA list, or some other work around?

Thank you for the help

**Comment by cfillion** [comment]
See if disabling "Verify the authenticity of SSL/TLS certificates" helps with the SSL error, and triple-check the proxy type, host and port. ReaPack uses the system's CA list.

The connection errors reapack reports are quite generic, I'm working making them more explanatory for the next update.

**Comment by stefankovatchev** [comment]
Thank you very much, I'll try that.

**Comment by stefankovatchev** [comment]
Unchecking that option worked, thanks again for the help! Sorry for the
trouble.

On Wed, Aug 24, 2016 at 7:52 PM, Stefan Kovatchev <stefankovatchev@gmail.com
